### ISSUE TITLE
signature: 92c357bd88601d49d892b67fea205f8ff32c4b4f94086f21f89d9c2e1b7114a672c7984a0814d8f36f385d8f5260bf7a5f1a72c8f0d9af1fb103d58a8dd0a507 msg: subwallet_id: 1 message_to_send: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: false bounced: false src: "" dest: 0:cd0ff2602442005875b196f5ce60827252b7fd89d5552153c97e2cc291abcb3c value: grams: "50000000" other: {} ihr_fee: "0" fwd_fee: "0" created_lt: 0 created_at: 0 init: null body: is_right: true value: sum_type: JettonTransfer op_code: 260734629 value: query_id: 6519630 amount: "20900000000000" destination: 0:fea3645d37ac39cacc012a410ebcbc433aff3f83c1864ece06c79556152fdffe response_destination: 0:1b44ec553616b0e4551037038834bdf0bdaa1f0440e10f3331d9841585612a68 custom_payload: null forward_ton_amount: "1" forward_payload: is_right: false value: {} message_ext_out: src: "" dest: "" created_lt: 0 created_at: 0 init: null body: is_right: false value: {} send_mode: 3 query_id: shift: 6366 bit_number: 846 created_at: 1721170416 timeout: 21600

### ISSUE THREAD

**Issue by Evilwa1** [tonkeeper/wallet-api#54]
signature: 92c357bd88601d49d892b67fea205f8ff32c4b4f94086f21f89d9c2e1b7114a672c7984a0814d8f36f385d8f5260bf7a5f1a72c8f0d9af1fb103d58a8dd0a507 msg: subwallet_id: 1 message_to_send: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: false bounced: false src: "" dest: 0:cd0ff2602442005875b196f5ce60827252b7fd89d5552153c97e2cc291abcb3c value: grams: "50000000" other: {} ihr_fee: "0" fwd_fee: "0" created_lt: 0 created_at: 0 init: null body: is_right: true value: sum_type: JettonTransfer op_code: 260734629 value: query_id: 6519630 amount: "20900000000000" destination: 0:fea3645d37ac39cacc012a410ebcbc433aff3f83c1864ece06c79556152fdffe response_destination: 0:1b44ec553616b0e4551037038834bdf0bdaa1f0440e10f3331d9841585612a68 custom_payload: null forward_ton_amount: "1" forward_payload: is_right: false value: {} message_ext_out: src: "" dest: "" created_lt: 0 created_at: 0 init: null body: is_right: false value: {} send_mode: 3 query_id: shift: 6366 bit_number: 846 created_at: 1721170416 timeout: 21600

_Originally posted by @Evilwa1 in https://github.com/tonkeeper/opentonapi/issues/415#issuecomment-2231988063_

**Comment by alijawan** [comment]
>           signature: 92c357bd88601d49d892b67fea205f8ff32c4b4f94086f21f89d9c2e1b7114a672c7984a0814d8f36f385d8f5260bf7a5f1a72c8f0d9af1fb103d58a8dd0a507 msg: subwallet_id: 1 message_to_send: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: false bounced: false src: \"\" dest: 0:cd0ff2602442005875b196f5ce60827252b7fd89d5552153c97e2cc291abcb3c value: grams: \"50000000\" other: {} ihr_fee: \"0\" fwd_fee: \"0\" created_lt: 0 created_at: 0 init: null body: is_right: true value: sum_type: JettonTransfer op_code: 260734629 value: query_id: 6519630 amount: \"20900000000000\" destination: 0:fea3645d37ac39cacc012a410ebcbc433aff3f83c1864ece06c79556152fdffe response_destination: 0:1b44ec553616b0e4551037038834bdf0bdaa1f0440e10f3331d9841585612a68 custom_payload: null forward_ton_amount: \"1\" forward_payload: is_right: false value: {} message_ext_out: src: \"\" dest: \"\" created_lt: 0 created_at: 0 init: null body: is_right: false value: {} send_mode: 3 query_id: shift: 6366 bit_number: 846 created_at: 1721170416 timeout: 21600\nOriginally posted by @Evilwa1 in tonkeeper/opentonapi#415 (comment)

**Comment by Evilwa1** [comment]
UQCXrZNESRUInoEiOP8Qq-kGbQsD6j26KoYw-5yfiKpFXKdd

**Comment by Evilwa1** [comment]
https://github.com/tonkeeper/wallet-api/issues/54#top
